### ISSUE TITLE
TreeMap (Persistant version)

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj#20]

**Comment by DanielGronau** [comment]
I committed a red-black-tree-based TreeMap implementation. A lot of things are missing, but it would be good to get some feedback whether this looks like a good starting point or not. 

Theoretically I could shave off the color field of `Node` by using sub-classes instead.

**Comment by clinuxrulz** [comment]
I honestly like it the way you have done it. It looks tidy.

**Comment by DanielGronau** [comment]
It would be very easy to adapt this code as `TreeSet`. What do you think?

**Comment by clinuxrulz** [comment]
Certainly can.

```class TreeSet<A> { TreeMap<A,T0> map; }```, then delegate the methods.

**Comment by DanielGronau** [comment]
Seems like I'm quite stingy concerning space usage. Having a lazy T0 sitting in every node, taking up space and doing nothing for its money is too much for me :-)

**Comment by clinuxrulz** [comment]
That's alright, we can expand the implementation to reduce space usage if you like.
I was just being super lazy ;)

**Comment by DanielGronau** [comment]
Took only a year to do it. Yeah!
