### ISSUE TITLE
Thoughts on improving optics package

### ISSUE THREAD

**Issue by DanielGronau** [highj/highj#29]
@jbgi When I updated the JavaDoc of the optics package, I had some ideas and questions:
- The composition methods look very repetitive. Could mixin inheritance help here? Of course a class `Foo<A>` can't implement `__<Foo.µ,A>` and a `__<SuperFoo.µ,A>` at the same time, so we would need to split off interfaces from the current classes. 
- It would be cool to have some predefined lenses, e.g. for tuples.
- It seems Lens uses the conventional getter-setter implementation, not the van Laarhoven style lenses, which seem to be quite hip at the moment (and for a good reason, I suppose). 

Implementing them is not difficult (I didn't want to go polymorphic, which is certainly  possible):

``` java
import org.derive4j.hkt.__;
import org.highj.data.structural.Const;
import org.highj.data.tuple.T1;
import org.highj.function.Functions;
import org.highj.typeclass1.functor.Functor;

import java.util.function.Function;

public interface VanLaarhovenLens<S,A>  {

    <F> Function<S, __<F, S>> apply(Functor<F> functor, Function<A, __<F, A>> targetFunction);

    default Function<S, S> modify(Function<A,A> function) {
        Function<A, __<T1.µ, A>> targetFunction = a -> T1.of(function.apply(a));
        return s -> T1.narrow(apply(T1.monad, targetFunction).apply(s)).get();
    }

    default Function<S, A> view() {
        Function<A, __<__<Const.µ, A>, A>> function = Const::new;
        return s -> Const.narrow(apply(Const.functor(), function).apply(s)).get();
    }

    default Function<S,S> set(A value) {
        return modify(Functions.constant(value));
    }
}
```

An instance:

``` java
public static <A,B> VanLaarhovenLens<T2<A,B>, A> first() {
    return new VanLaarhovenLens<T2<A, B>, A>() {
        @Override
        public <F> Function<T2<A, B>, __<F, T2<A, B>>> apply(Functor<F> functor, Function<A, __<F, A>> targetFunction) {
            return pair -> functor.map(a -> T2.of(a,pair._2()), targetFunction.apply(pair._1()));
        }
    };
}
```

(code stolen from here: http://blog.jakubarnold.cz/2014/07/14/lens-tutorial-introduction-part-1.html )

**Comment by jbgi** [comment]
Yes, the subtyping relation is not ideal (for lack of type-synonym) and probably using templates interfaces we could avoid it.

The implementation (an almost straight port of Monocle) do not use the van Laarhoven representation but I believe the api is isomorphic to it. I think @julien-truffaut used getter/setter for performance reasons (after benchmark).

**Comment by clinuxrulz** [comment]
```PLens``` actually has a ```modifyF```, so maybe its not too bad, it just doubles up on code for performance?.

From ```PLens```:
```
public abstract <X> F1<S, __<X, T>> modifyF(Applicative<X> applicative, Function<A, __<X, B>> f);
```

From Tutorial:
```
type Lens s t a b = Functor f => (a -> f b) -> s -> f t
```

**Comment by DanielGronau** [comment]
Yes, I saw this, but was wondering why it uses `Applicative` instead of `Functor`

**Comment by clinuxrulz** [comment]
A mistake maybe? It is a functor in monacle.

```  /** modify polymorphically the target of a [[PLens]] using Functor function */
  def modifyF[F[_]: Functor](f: A => F[B])(s: S): F[T]```

**Comment by DanielGronau** [comment]
So when this is an abstract method, we actually _have_ van Laarhoven lenses, we just force the user to write getters and setters themselves for performance reasons? I mean, we could provide default implementations, but with a comment that they should be overridden if possible. I mean, it is often the case that a lens is used _just_ for viewing or _just_ for modifying, so it would be good if the user needs to overwrite the heavily used methods only.

**Comment by julien-truffaut** [comment]
@jbgi is correct, in monocle we tried several implementations van laarhoven, profunctor based, pair of getter / setter. It turns out that the most efficient implementation was a mix of getter / setter and van laarhoven.

**Comment by clinuxrulz** [comment]
@DanielGronau it might be better just to define a lens in terms of ```get``` and ```set``` (```PLens.pLens```). We still get ```modifyF``` for free (it gets defined in terms of ```get``` and ```set```, we lose no expressive power). Plus Java lambdas do not handle generic type parameters.

The only thing I would change is to relax the type constraint ```Applicative``` to ```Functor```. And maybe a 2nd capture-less overloaded variant of the get / set pair (to lower the memory allocations from 2 to 1 per execution of set). Its only a suggestion.

**Comment by julien-truffaut** [comment]
You're right, you only need a `Functor` constraint for `modifyF` for `Lens`, you need `Applicative` for `Prism` and `Traversal`

**Comment by jbgi** [comment]
@DanielGronau and yes the Applicative constraint was a bad copy-paste (from Traversal maybe) on my part.
I think it would be a good idea to add a factory on  PPlens that take a polymorphic ```Functor f => (a -> f b) -> s -> f t````

**Comment by DanielGronau** [comment]
@jbgi Would it be okay to make optics a sub-project? 

If yes, would you split it off, or should I do it?

**Comment by jbgi** [comment]
@DanielGronau I think optics are so useful in so many use cases, in modern FP, that I think they should be easily accessible be in base/prelude. They are currently underused and I fear that a separate optics sub-project will lower adoption rate.

**Comment by DanielGronau** [comment]
I see your point. Maybe we should instead pull the package one level up to `org.highj.optic`, it is kind of hard to spot inside `data`.  Further, I think lenses deserve a Wiki page with a short introduction. Of course it makes no sense to repeat the monocle documentation, we can reference to it and just point out relevant differences (if there are any).
