### ISSUE TITLE
Indexed Monads?

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj#45]
I have an interesting use case for Indexed Monads. Which is a monadic language that gets compiled into an concatenative language which can be saved and uploaded to a server, downloaded by a client and then executed on their machine. Its like user specific updates. I call it the Remote Update monad.

https://gist.github.com/clinuxrulz/90e357d93aa559af9feb7b3786983351

```RU``` is the remote update monad.
```RUStmts``` is the concatenative language that ```RU``` gets compiled into using ```RUCompiler```.
```RUInterpreter``` interprets the concatenative code on the user's machine.

```RUStmts``` can be thought of as a Indexed Monoid which tracks the transformation of the stack's type signature, and which turns out to be the same type as a ```Category```.
Note that this is not a new idea as seen here:
https://github.com/leonidas/codeblog/blob/master/2012/2012-02-17-concatenative-haskell.md

The code is more of an experiment at the moment, and its untested.

The problem comes where I lose type-safety in ```RUCompiler``` because the state will keep change type signature as compilation progresses, thus the need for Indexed monads to track the change in type signature.

Which leads me to the question: Would indexed monads be inside or outside the scope of HighJ?

If they are inside the scope, then we could need the following. ```IxFunctor```, ```IxApply```, ```IxApplicative```, ```IxBind``` and ```IxMonad``` to begin with. Then possibly ```IxStateT``` and other indexed monad transformers. Its a lot of work, and I would be perfectly fine if its outside the scope of HighJ.

Heres sort of the pattern:

https://hackage.haskell.org/package/indexed-0.1/docs/Control-Monad-Indexed.html

I would probably swap the parameters in ```ibind``` for consistency with non-indexed code.

**Comment by DanielGronau** [comment]
Indexed monads seem quite useful, so I see no problem having these in highJ - we can factor them out in a sub-project later (same as for optics). Or we could prioritize the move to a highJ organization, so all contributors could work on sub-projects asap. 

BTW, the "McBride"-version of indexed monads seems to be strictly more powerful (see the answer of Edward Kmett here: http://stackoverflow.com/questions/28690448/what-is-indexed-monad ) than the "Control-Monad-Indexed" one, maybe it is worth considering.

**Comment by clinuxrulz** [comment]
Yes. I think a sub-project. It is a bit too specialized. And McBride looks very interesting, it feels sort of like that profunctor approach to lens.

**Comment by DanielGronau** [comment]
I close this issue, as indexed monads won't be part of the main project.
