### ISSUE TITLE
Sub-project idea. highj-typeable

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj#50]
One thing that gets annoying quickly is having the same or very similar code for deriving Equal, Ord and Hash instances of your data structures. To resolve this I was thinking of a special data structure called ```Typeable``` that provides the shape of the data structure your modeling as a GADT.

This ```Typeable``` can then be used to auto-magically derive ```Ord```, ```Equal```, ```Hash``` and possibly more from a given ```Covariant``` functor or an ```Invariant``` functor. (automatic Serialization comes to mind too)

This might be nice to have in ```highj-typeable```.

It is then possible to auto-derive the ```Typeable``` using Java's reflection if the user wishes. Otherwise the user can define ```Typeable``` by hand just incase their data type is not so plain.

**Comment by clinuxrulz** [comment]
For Serialization as an example use-case. Someone could write a pair of say ```SourceEff``` and ```SinkEff``` containing a collection of effects for reading/writing to/from an unknown data source. Then bundle those two into something like ```LoadSave```, then this ```LoadSave``` becomes an instance of an ```Invariant``` functor.

Information ```Typeable``` can then be used to automatically derive a ```LoadSave```. Which gives the end-user the ability to read/write any ```Typeable``` into any language independent data format like XML and JSON.

I've used such a pattern before and it does lower the amount of repetitive code someone would have to write.

One problem comes with multiple versions of the file format. So ```Typeable``` would have to have some mechanism to branch by version number (different invmaps on each version), and possibly tag data/sub-data with default values. A ```LoadSave``` can store a warning if a field is not present and take on the default value, so the program can just continue with a warning, and the user of the program does the appropriate edit to mend the field, then the file can heal itself on save.

**Comment by clinuxrulz** [comment]
One more use-case for ```Typeable``` that comes to mind is the automatic generation of user-interface forms. Mainly just as a default form to use until someone has the time spare to do a hand written UI.

Its just a no-frills user-form with no input validation or anything. For just when you need to prototype something quickly. I'm not saying we should do this as a sub-project, its just another use-case for ```Typeable```.

**Comment by DanielGronau** [comment]
Sounds interesting. Could be also useful when we want to have a `Show` type-class
