### ISSUE TITLE
[Idea] Fluent Interface for Monad instances.

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj#55]
This is untested at the moment, its just an idea. One advantage FJ has over us at the moment is a fluent interface for their monads (admittably by violating the DRY principle).

Maybe we could design a wrapper to also give us the fluent interface pattern.

One way:

```
interface FluentInterfaceM<M,A> {
  __<M,A> unbox(Monad<M> mMonad);

  static <A> FluentInterfaceM<M,A> pure(A a) {
    return (Monad<M> mMonad) -> mMonad.pure(a);
  }

  default <B> FluentInterfaceM<M,B> map(F<A,B> f) {
    return (Monad<M> mMonad) ->
      mMonad.map(f, FluentInterface.this.unbox(mMonad))
  }

  default <B> FluentInterfaceM<M,B> bind(F<A,FluentInterfaceM<M,B>> f) {
    return (Monad<M> mMonad) ->
      mMonad.bind(
        FluentInterface.this.unbox(mMonad)
        (A x) -> f.f(x).unbox(mMonad)
      );
  }
}
```

Example use:

```
__<__<__<StateT.Mu,Integer>,Maybe.Mu>,Unit> test =
  FluentInterfaceM.pure(5)
    .map((Integer x) -> x + 1)
    .map((Integer x) -> x * 2)
    .map((Integer x) -> x - 3)
    .unbox(StateT.monad(Maybe.monad));
```

Maybe `FIM` instead of `FluentInterfaceM` to keep it short.

**Comment by jbgi** [comment]
@clinuxrulz Won't this functionality be included with the do notation you have been working on?

**Comment by clinuxrulz** [comment]
Maybe ```FluentFunctor```, ```FluentApply```, etc. are more appropriate names.

**Comment by clinuxrulz** [comment]
@jbgi true. It just seems a bit noisy visually. (annoymious class required instead of lambda)

**Comment by jbgi** [comment]
@clinuxrulz I see. 

I think a short suffix standing for "wrapper" would be ok: `MonadW` or `FunctorW` (like in http://www.functionaljava.org/javadoc/4.6/functionaljava/fj/data/IOW.html)

**Comment by clinuxrulz** [comment]
@jbgi yes, that is a nice convention.

**Comment by clinuxrulz** [comment]
```ArrowW``` would be interesting too. That would effectly form a typesafe concatenative DSL, with next to no noise.

**Comment by DanielGronau** [comment]
For me this looks like it should be somehow possible to integrate it in the reader monad, but I couldn't quite get it right. The best I could come up with is

```java
 interface ReaderM<M, A> extends ReaderT<Monad<M>, M, A> {
        static <M, A> ReaderM<M, A> pure(A a) {
            return r -> r.pure(a);
        }

        default <B> ReaderM<M, B> bind(Function<A, __<M, B>> fn) {
            return r -> r.bind(run(r), fn);
        }

        default <B> ReaderM<M, B> map(Function<A, B> fn) {
            return r -> r.map(fn, run(r));
        }
    }
```

But I don't know if this even makes sense...

**Comment by clinuxrulz** [comment]
@DanielGronau, yea it is the reader monad carrying the implemention under the hood. However the exposed methods will be different for each type of wrapper. Some code reuse is still possible though E.g. ```interface MonadContW<M,A> extends MonadW<M,A> { ... }```

**Comment by clinuxrulz** [comment]
Actually, after a bit of experimenting. I'm struggling with code reuse. (as in ```interface MonadContW<M,A> extends MonadW<M,A> { ... }```). The type system does not like me overriding ```unbox``` / ```unwrap```.

**Comment by DanielGronau** [comment]
How about this:

```java
   interface MonadW<M, A, MM extends Monad<M>> {
        static <M, A> MonadW<M, A, Monad<M>> pure(A a) {
            return mMonad -> mMonad.pure(a);
        }

        default <B> MonadW<M, B, MM> bind(Function<A, MonadW<M, B, MM>> f) {
            return mMonad -> mMonad.bind(
                    MonadW.this.unbox(mMonad),
                    (A x) -> f.apply(x).unbox(mMonad)
                    );
        }

        default <B> MonadW<M, B, MM> map(Function<A, B> f) {
            return mMonad -> mMonad.map(f, MonadW.this.unbox(mMonad));
        }

        __<M, A> unbox(MM mMonad);
    }

    interface MonadPlusW<M, A, MP extends MonadPlus<M>> extends MonadW<M, A, MP> {
        @Override
        __<M, A> unbox(MP mMonadPlus);

        default MonadPlusW<M,A, MP> mzero() {
            return mPlus -> mPlus.mzero();
        }
    }
```

**Comment by clinuxrulz** [comment]
@DanielGronau nice work. Seems like a viable solution.

**Comment by DanielGronau** [comment]
Thank you!

**Comment by clinuxrulz** [comment]
Version 3 of do notation now has a fluent style. Making monad wrappers less important. But I'll leave this open for discussion of other kinds of wrappers for other type-classes.
