### ISSUE TITLE
Yet Another Do Notation

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj#57]
I have another style of Do Notation.
https://github.com/clinuxrulz/DoNotation/tree/master/src/main/java/org/highj/do_

It is sort of like the 1st attempt that had a fluent interface, but this one allows unlimited variables.
This is is based an concatenative programming. However I'm not sure if its easier or harder to use than the 1st and 2nd Do notation attempts.

```Do_``` <-- user uses for Do Notation
```DoIndexed``` <-- hidden internal implementation based on indexed monoids
```__(__<M,A> m)``` <-- performs effect and ignores result.
```map1(F<A,B> f)``` <-- takes 1 value off the top of the stack, applys f to it, then puts it back on the stack.
```map2(F2<A,B,C> f)``` <-- takes 2 values off the top of the stack, applys f to it, then puts the result on the stack.
```bind1(F<A,__<M,B>> f)``` <-- takes 1 value off the top of the stack, applys f performs effect and ignores result.
```bind2(F<A,B,__<M,C>> f)``` <-- takes 2 values off the top of the stack, applys f performs effect and ignores result.
```pushBind1(F<A,__<M,B>> f)``` <-- takes 1 value off the top of the stack, applys f performs effect and puts result on stack.
```pushBind2(F2<A,B,__<M,C>> f)``` <-- takes 2 values off the top of the stack, applys f performs effect and puts result on stack.
```pushM(__<M,A> m)``` <-- performs effect and puts result on stack.

It all uses a stack in the back end like concatenative languages do (except type safe. Think heterogeneous lists).

This style can save on doing a fluent wrapper too. What do you think?

**Comment by clinuxrulz** [comment]
The indexed monoid trick for concatenative programming has been done before too.
Reference:
https://github.com/leonidas/codeblog/blob/master/2012/2012-02-17-concatenative-haskell.md

**Comment by DanielGronau** [comment]
Looks very interesting, but I have to try it out myself to get a feeling for it. A nice do-notation would be definitely one of the killer features of the library, so I think it's important to look into different approaches.

**Comment by clinuxrulz** [comment]
I've had a bit of test of this style.

```
    public static <M> __<M, Unit> update(MonadRec<M> mMonadRec, MonadSceneEffect<M> monadSceneEffect, int trussId) {
        Monad<M> monad = monadSceneEffect;
        return Do_.<M>do_()
            .pushM(monadSceneEffect.withEntity(trussId, new MonadSceneEffect.WithEntity<Option<GableTrussParamsComponent>>() {
                @Override
                public <M2> __<M2, Option<GableTrussParamsComponent>> apply(MonadRec<M2> monadRec, MonadEntityEffect<M2> monadEntityEffect) {
                    return Do_.<M2>do_()
                        .pushM(monadEntityEffect.getComponent(EcsComponentTypes.AusSteel()))
                        .map1(Leibniz.refl(), (Option<EcsComponent> x) -> x.bind(EcsComponents::getAusSteel))
                        .pushM(monadEntityEffect.getComponent(EcsComponentTypes.GableTrussParams()))
                        .map1(Leibniz.refl(), (Option<EcsComponent> x) -> x.bind(EcsComponents::getGableTrussParams))
                        .map2(
                            Leibniz.refl(),
                            (Option<AusSteelComponent> ausSteelOp, Option<GableTrussParamsComponent> gableTrussParamsOp) ->
                                ausSteelOp.bind(
                                    gableTrussParamsOp,
                                    unused -> gableTrussParams -> gableTrussParams
                                )
                        )
                        .runWithResult(Leibniz.refl(), monadRec);
                }
            }))
            .map1(Leibniz.refl(), Option.join())
            .bind1(
                Leibniz.refl(),
                (Option<GableTrussParamsComponent> paramsOp) ->
                    paramsOp.<__<M, Unit>>option(
                        () -> monad.pure(Unit.unit()),
                        (GableTrussParamsComponent params) ->
                            Do_.<M>do_()
                                .__(monadSceneEffect.destroyChildrenOf(trussId))
                                .__(createMembers(mMonadRec, monadSceneEffect, trussId, params))
                                .runNoResult(mMonadRec)
                    )
            )
            .runNoResult(mMonadRec);
    }
```

That what it looks like. I'm just a little worried that it would be a bit of a mental hurdle for the end-user to track stack variables in their mind (as its point-free style).

In IntelliJ you can go ```.getClass()``` on the end of a do-notation line temporarily and the IDE's autocomplete will show you the type signature of the stack at that line (you will need to drag the bottom right corner of the popup to resize it and to see the whole signature).

It definitely feels more compact and tidy. Its just a matter of "Will the end user be OK with this style?".

**Comment by DanielGronau** [comment]
I guess with a good documentation the users could pick it up. BTW, are there methods to manipulate the stack (e.g. swap the last two variables...)?

I'm a little unsure what the Leibniz instances are for. It has something to do with type equality, right?

**Comment by clinuxrulz** [comment]
No methods for stack manipulation yet. But they are easy to add.

Here are some that might be nice. http://docs.factorcode.org/content/article-shuffle-words.html

```Leibniz``` is being used to get the Java compiler to pattern match on type-variables. Its not the normal use-case of ```Leibniz```, but it comes in handy here.

**Comment by clinuxrulz** [comment]
Also ```Do_.mapAll()``` can be used to implement stack manipulation. The **All** word means you have access to the entire stack.

**Comment by clinuxrulz** [comment]
Something else that is interesting is that ```DoIndexed``` is equivalent to a quotation in concatenative languages, maybe I should rename it and make it not package private.

**Comment by clinuxrulz** [comment]
Not done yet in the implementation link provided, but this is what ```dup``` would look like.

```
    public <S,X> Do_<M,P2<P2<S,X>,X>> dup(Leibniz<A,P2<S,X>> leibniz) {
        return mapAll((A a) -> {
            P2<S,X> x = leibniz.coerce(a);
            return P.p(x, x._2());
        });
    }
```

```P2``` is ```T2```

**Comment by clinuxrulz** [comment]
And to help see the pattern, here is swap.

```
    public <S,X,Y> Do_<M,P2<P2<S,Y>,X>> swap(Leibniz<A,P2<P2<S,X>,Y>> leibniz) {
        return mapAll((A a) -> {
            P2<P2<S,X>,Y> x = leibniz.coerce(a);
            return P.p(P.p(x._1()._1(), x._2()), x._1()._2());
        });
    }
```

**Comment by clinuxrulz** [comment]
Maybe not dive into this DO-notation straight away. Because I've noticed IntelliJ using 100% cpu while idle.

Will have to do some experiments and see whats best IDE-wise. I'm currently on IntelliJ 14.1.3. I'll update my IDE later and see if I still get the same problem.

**Comment by clinuxrulz** [comment]
A very large test of the Do-Notation with stack manipulation functions.
https://gist.github.com/clinuxrulz/df5ed0b097b57f77b593b7dc88e08822

**Comment by DanielGronau** [comment]
Sorry for being not very responsive lately, I'll be quite busy for the next few weeks. So please go forward with this and the other sub-projects.

**Comment by clinuxrulz** [comment]
@DanielGronau Thats alright.

I will not put in this Do-Notation straight away. I'm just not sure what our end-users would prefer.

**Version 2:** Very noisy, but its clear where and what the binding variables are.

**Version 3:** Much less noise (i think), but the binding variables are mostly hidden because its point-free.

The sub-projects I'll go forward with and close their issues.

**Comment by clinuxrulz** [comment]
I've had a very good run with testing version 3 of do notation in production code recently. It was much less noisy than version 2. So I've decided to just switch it over in highj.
