### ISSUE TITLE
Should we rename List.of(Iterable) and List.of(java.util.List) methods to List.from(...)?

### ISSUE THREAD

**Issue by DanielGronau** [highj/highj#69]
Today I run in an issue when writing `List.of(Maybe.Just(42))`, which didn't trigger the vararg-method, but the `List.of(Iterable)` version, as `Maybe` is an `Iterable`. 

So I would be inclined to rename `List.of(Iterable)` and `List.of(java.util.List)` to something else, e.g. `List.from(...)` to avoid such surprises. 

What do you think?

**Comment by clinuxrulz** [comment]
I agree. FunctionalJava 4.4 had the same issue. The moment they added ```List.list(Iterable)```, ```List.join(List.list(...))``` broke in existing code for some use cases.

Maybe ```List.fromIterable(...)```.

**Comment by DanielGronau** [comment]
Done
