### ISSUE TITLE
Problems with generated code

### ISSUE THREAD

**Issue by DanielGronau** [highj/highj#70]
The code generation is nice, but also messes some things up. So far I had some problems with the IntelliJ setup, which is okayish, as I can use Maven for some things. As IDEA devolops quickly, most howtos seems to be outdated. Now I found out that also the JavaDoc Maven goals don't work anymore. I hate dealing with such stuff :-/

Do you have some ideas or suggestions how to improve this? The project should really work out of the box, without fiddling around. Could switching to Gradle give us more control?

**Comment by jbgi** [comment]
@DanielGronau it may be related to Windows, `mvn javadoc:javadoc` does work on my linux machine (apart from some warnings). What is exactly is the error?

**Comment by DanielGronau** [comment]
`mvn javadoc:javadoc` gives warnings like 
```
[WARNING] import static org.highj.Hkt.asCokleisli;
[WARNING] ^
[WARNING] symbol:   class Hkt
[WARNING] location: package org.highj
[WARNING] D:\Code\highj\src\main\java\org\highj\control\arrow\cokleisli\CokleisliArrow.java:13: error: static import only from classes and interfaces
```
However, I got these as errors when calling `mvn javadoc:jar`, but strange enough now they seem to be only warnings there as well.

**Comment by jbgi** [comment]
I pushed an upgrade of compiler plugin that should avoid some maven-related issues with annotation processor and generated code. I did not find how to disable the javadoc warning.
It is related to static import of generated methods. One "solution" would be to not use static imports for generated methods.

**Comment by DanielGronau** [comment]
Thank you!
