### ISSUE TITLE
Implement These data type

### ISSUE THREAD

**Issue by DanielGronau** [highj/highj#78]
Seems to be a good fit: http://hackage.haskell.org/package/these-0.7.4/docs/Data-These.html

**Comment by clinuxrulz** [comment]
I've come across a use-case for ```These```. Say you have a UI element with a FRP Stream to set its value, call it ```sSetValue```, and another stream for representing when the UI element value changed ```sValueChanged```. Then you want to distinguish between the end-user setting the value in the UI element, or code setting the value in the UI element. ```These``` could represent the result of a merge of ```sSetValue``` and ```sValueChanged``` (combining simultaneous events), and then the distinction can be made be doing a few maps and filters. There would also be some other use-cases too.
