### ISSUE TITLE
Feature request: Monoidal and Cartesian Categories

### ISSUE THREAD

**Issue by clinuxrulz** [highj/highj#79]
These would be great for experimentation.

See: http://conal.net/papers/compiling-to-categories/

Also see: https://gist.github.com/paf31/5c1279796d66fe04a177e34b0d674ac6

It gives you a lambda calculus that can be compiled into a Cartesian category at runtime. We'd probably want a few more levels in the typeclasses though.

**Comment by DanielGronau** [comment]
I don't fully grasp the paper, but we can give it a try. The basic type-classes seem to be easy to implement. It would be better to have a working Haskell module for reference, though.

**Comment by clinuxrulz** [comment]
This is the one that we can compile lambda calculus to for that incremental computation and automatic derivatives:
http://hackage.haskell.org/package/categories-1.0.7/docs/Control-Category-Cartesian-Closed.html

There is a lot of levels to the typeclass. I'm not sure if we should go as deep. We could just go ```CCC``` extending ```Category``` directly, and just combine all the methods in ```CCC```.

**Comment by clinuxrulz** [comment]
The ```CCC``` in the 2nd link is probably enough:

https://gist.github.com/paf31/5c1279796d66fe04a177e34b0d674ac6

The hackage one seems like overkill.

**Comment by DanielGronau** [comment]
I opened a branch `category-ccc` for playing around, and started with the easiest class :-D

**Comment by clinuxrulz** [comment]
Cheers. I've been to busy to play with this lately... you were very quick, nice work.

**Comment by clinuxrulz** [comment]
I may play with you some time on the same branch... make sure we debug it first before it becomes a part of master branch.

**Comment by clinuxrulz** [comment]
I had a quick browse of your code by eye, and nice work! What I like about CCC is that it preserves the meaning of the code, and when you feed it different category to can have different evaluation strategies which gives different interpretation of the same code.

One category I've been bugging people to try out in other repositories is:
```
data IncF a b = IncF (a -> (b, IncF2 a b))
data IncF2 a b = IncF2 (Δa -> (Δb, IncF2 a b))
```
Which is a little tricky in Java because we do not have type families. But what it provides is an interpretation that incrementally updates a computation on change in input. The reason I'm interested in this one is that it can replace virtual dom, eliminating the need for diffing algorithms. Diffing algorithms partly involve finding the longest common subset of a set, which I believe is NP-Hard. So as the number of interactive elements on your screen become large, a diffing algorithm suffers quite significantly.

Conal Elliott demonstrates quite a few different categories in his paper. In his paper lambda calculus is compiled to CCC via a compiler plugin. And the drawing of the graphs in his paper is actually produced directly from the code via a category suitable for producing graph drawings.

In the 2nd link, Phil Freeman shows how to compile lambda calculus to CCC at runtime rather than a compile plugin. Which would be achievable for us in Java. His ```Untyped``` debugging category is similar to Conal's graph drawing category in that it lets you see the source code of the computation.

**Comment by DanielGronau** [comment]
To be honest, I have no idea what I'm doing, but it is kind of fun. I'll see how it goes with `Cast`

**Comment by clinuxrulz** [comment]
Would be awesome one ```lam``` and ```($)``` is going. It would mean we can runtime compile lambda calculus into CCC.

**Comment by clinuxrulz** [comment]
We may have a few more options for ```lam```. Here is the blog post that goes with Phil Freeman's code.
https://blog.functorial.com/posts/2017-10-08-HOAS-CCCs.html
We may find a way that works nicer for Java .

**Comment by clinuxrulz** [comment]
In java we may not even need ```Cast``` because we can do things like ```<A extends Something>```. I'll have a play around with the same code soon.

**Comment by clinuxrulz** [comment]
I created a KTest in the tests package. It shows a couple of tests from the 2nd link.

**Comment by clinuxrulz** [comment]
I think the ```Lam2CCC``` class is too tricky to use for nontrivial code, and the end-user would have to supply really long type signtures to make it work. What might be better is a simple deeply embedded DSL for the lambda calculus itself, then transform the lambda calculus into CCC via the transformation methods given in Conal's paper (1st link).

Any ideas on a nice DSL for lambda calculus?

**Comment by DanielGronau** [comment]
I could only find simple untyped DSLs like https://github.com/noti0na1/LambdaCalculus-java

I'm not sure wether this can help us.

While searching I found this interesting, but unfortunately outdated paper: http://web.cs.ucla.edu/~palsberg/tba/papers/wright-jagannathan-ungureanu-hertzmann-tic98.pdf

**Comment by clinuxrulz** [comment]
Not sure if ```STLC``` can be fully inspected to make it convertable to a ```CCC```, because of that lambda held by ```Lam```.

**Comment by clinuxrulz** [comment]
Actually, something like this might work:
```
data STLC repr a where
  Lam :: (STLC repr a -> STLC repr b) -> STLC repr (a -> b)
  Ap :: STLC repr (a -> b) -> STLC repr a -> STLC repr b
  Lift :: repr a -> STLC repr a
  Var :: Int -> STLC repr a
```
Then if I send a ```Var``` attached to a unique integer into the lambda held by ```Lam```, then it would reveal the the structure inside the lambda held by ```Lam```.

**Comment by clinuxrulz** [comment]
Here is a rough sketch of the Code in Java: https://gist.github.com/clinuxrulz/c29f063c5b3e8fc54cd07010f77b4c54

```System.out.println(LC.lam(x -> LC.lam(y -> x)).toString());```
produces:
```(\v0 -> (\v1 -> v0))```

which means the lambda can be fully inspected, and compiled down to CCC using the steps in the paper in the 1st link.

**Comment by clinuxrulz** [comment]
I've almost got her work out. Just very challenging. And it looks like we might need Cartesian as well, not just CCC, and extend CCC from Cartesian. Because it is not possible to implement ```apply```, ```curry```, ```uncurry``` for some of the interesting category, yet when optimising the ```CCC``` in most cases we can eliminate the requirement of theses methods be left with just a Cartesian Category.... so maybe just 1 level deeper in the typeclass.

**Comment by clinuxrulz** [comment]
Getting closer, check it out :wink:

    System.out.println(toCCC(K.ccc(), LC.lam(x -> LC.lam(y -> x))).map(Hkt::asK).map(K::optimize).map(K::prettyPrint).getOrElse(""));

Produces:

    uncurry id . (curry (fst . snd) &&& id)

Not quite optimised yet.

**Comment by clinuxrulz** [comment]
One optimization we can add is:
```apply . (curry h `fork` g)
= h . (id `fork` g)```

It should be enough to help us move from CCC to Cartesian.

**Comment by clinuxrulz** [comment]
Implementing the rest of the tests from the 2nd link reveals a seg fault in the java compiler.

**Comment by clinuxrulz** [comment]
OK. Defining the ```IncF``` in Java was easier than I thought it would be. We could be onto something exciting here. A replacement for virtual dom just looks just like elm architecture code-usage-wise.

Here is a taste of how ```IncF``` could be defined in Java:

https://gist.github.com/clinuxrulz/21cad00a3c75b2395187ace02a6acb97

I don't believe this stuff will be over your head seeing the code you've already written. Is it the ```hom``` and ```tensor``` that is confusing?... ```hom``` is just like a lambda or function (```F1```), and ```tensor``` is just like our tuples (```T2```). The only reason they exist as type variable is just to increase the flexibility for instances of Cartesian and CCC, and there may be time when theses type are defined in terms of the category they are for too.

We have enough under the hood at the moment to create an experimental project called something like ```vdom-experiment``` and see how far we can go. It can use HighJ for creating a lambda calculus DSL that can perform incremental updates, and be sitting on top of GWT so we can test it on a real dom.

If the experiment is a success, we can translate the ideas to a highly used language for web app development, such as TypeScript. Rinse and Repeat.

**Comment by clinuxrulz** [comment]
I'm going to have a bit of a play here:
https://github.com/clinuxrulz/vdom_escape

its only dependency is the ```category-ccc``` branch of ```highj```. I'll let ya know how it turns out.

**Comment by clinuxrulz** [comment]
First successful compilation from lambda calculus to incremental functions.

```
        IncF<Integer, Integer> x1 =
            Hkt.asIncF(
                FreeCCC
                    .narrow(
                        LC.<__<__<__<FreeCCC.µ, IncF.µ>, T2Tensor.µ>, Hom>, T2Tensor.µ, Hom, Integer, Integer>toCCC(
                            FreeCCC.ccc(),
                            LC.lam(x -> x) // <-- code goes here. E.g. model -> view
                        ).get()
                    )
                    .reduceToCartesian(T2Tensor.tensorDontDependOnK, IncF.cartesian()).get()
            );
```

I'm just struggling with TeaVM, when I compile some code with a ```public static void main(String[] params)``` method, that method does not seem to get generated in the javascript produced.

Have you had some experience with TeaVM before?

I was gonna use it to demonstrate a incremental dom.

**Comment by clinuxrulz** [comment]
never mind ```mvn package``` was what i needed to type :smile:

**Comment by clinuxrulz** [comment]
Fighting type signatures at the moment. Its interesting that it is possible rearrange the code to hide the details of LC & CCC from the end user.

E.g. An incremental tuple constructor
```
    public static <Hom,A,B> LC<__<__<__<FreeCCC.µ, IncF.µ>, T2Tensor.µ>, Hom>, Hom, __3<T2Tensor.µ, __<__<__<FreeCCC.µ, IncF.µ>, T2Tensor.µ>, Hom>, Integer, Integer>> t2(
        LC<__<__<__<FreeCCC.µ, IncF.µ>, T2Tensor.µ>, Hom>,Hom,A> a,
        LC<__<__<__<FreeCCC.µ, IncF.µ>, T2Tensor.µ>, Hom>,Hom,B> b
    ) {
        CCC<__<__<__<FreeCCC.µ, IncF.µ>, T2Tensor.µ>, Hom>, T2Tensor.µ, Hom> ccc = FreeCCC.ccc();
        return LC.ap(LC.ap(LC.lift(ccc.curry(ccc.identity())), a), b);
    }
```

The ```LC``` stuff could all be wrapped up by a new type... call it something like ```ILC``` (incremental-lambda calculus). The type-signature becomes:

```public static <A,B> ILC<T2<A,B>> t2(ILC<A> a, ILC<B> b) { ... }```

With enough wrapping it might be possible to keep the end-user unaware they are using anything complicated, it would just feel like normal functional programming.

Still a bit of work to do, need to incremental constructors for the dom elements themselves.

**Comment by clinuxrulz** [comment]
We can probably do away with the k type parameter being passed to the Tensor & Hom.
This implementation does without it:
https://hackage.haskell.org/package/category-extras-0.53.0/docs/Control-Category-Cartesian-Closed.html

Also it would make that ```FreeCCC``` a bit easier to use (in vdom_escape). That change would get rid of the ```TensorDoesntDependOnK``` & ```HomDoesNotDependOnK``` type classes I needed to use ```FreeCCC``` for rule-rewrites before developing the ```IncF```.

**Comment by clinuxrulz** [comment]
OK. I think I've come to the conclusion that creating a lambda calculus dsl and compiling it to ccc is complete overkill for a vdom replacement. We can just use ```IncF``` directly and wrap it up however we like.

```
    public static <I> IncF<I,Element> el2(
        String element,
        __2<IncF.µ,I,Atomic<String>> text,
        __2<IncF.µ,I,IMap<String,Atomic<String>>> attributes,
        __2<IncF.µ,I,IMap<String,Atomic<Consumer<DomEvent>>>> handlers,
        __2<IncF.µ,I,IMap<Integer,Element>> children
    ) {
        return IncF.narrow(IncF.semigroupoid.dot(
            incFEl2(element),
            t2(text, t2(attributes, t2(handlers, children)))
        ));
    }

    public static <I,A,B> IncF<I,__3<T2Tensor.µ, IncF.µ, A, B>> t2(
        __2<IncF.µ,I,A> a,
        __2<IncF.µ,I,B> b
    ) {
        return IncF.narrow(IncF.cartesian.fork(a, b));
    }
```

Quite easy to define an incremental element that way. ```I``` here is just our environment type, (the type signature of the model).

I'll go down that path instead, no need to have a ```CCC``` or ```Cartesian``` type classes in highj, but could become useful one day.
