### ISSUE TITLE
Is abstracting over Eq => Eq1, Ord => Ord1 etc useful?

### ISSUE THREAD

**Issue by DanielGronau** [highj/highj#84]
We could write something like:

    public interface Lifted1<T,L> {
        <A> __<T,__<L,A>> lifted1(__<T,? super A> plain);
    }

    public interface Eq1<F> extends __<Eq1.µ, F>, Lifted1<Eq.µ, F> {
        interface µ {}

        <T> Eq<__<F, T>> eq1(Eq<? super T> eq);

        @Override
        default <T> Eq<__<F, T>> lifted1(__<Eq.µ, ? super T> eq) {
            return eq1(Hkt.asEq(eq));
        }
    }

Could this abstraction be helpful in any way?

**Comment by clinuxrulz** [comment]
Yes it can be useful. It can reduce the amount of code we have to write for defining ```Eq```, ```Ord```, etc. Good examples can be found in the transformers package on hackage.

https://hackage.haskell.org/package/transformers-0.4.3.0/docs/Data-Functor-Classes.html

I also came across something similar requiring me to define ```Show3```, but it might be a different beast.

https://gist.github.com/clinuxrulz/e1ae4eb86a833afe582e3cd2e55e180a#file-main-purs-L153

**Comment by clinuxrulz** [comment]
Yep that ```Show3``` was a different beast, don't worry about it.
```Eq1```, ```Ord1``` are useful for cutting down the code to write for ```Eq``` and ```Ord``` for any custom DSLs that are evaluated in the same runtime they are defined.
